version: 1
labels:
  - label: "newWallpapers"
    - wallpapers/**/*
      
  - label: "enhancement"
    files:
      - ".github/.*"
      
  - label: "readme_update"
    files:
      - "README.md*"
    
  - label: "CONTRIBUTION_update"
    files:
      - "CONTRIBUTION.md*"
      
      
    
       
