version: 1
labels:
  - label: "anime-additions"
    files:
      - "wallpapers/anime-wallpapers"
  - label: "nature-additions"
    files:
      - "wallpapers/nature-wallpapers"

  - label: "random-additions"
    files:  "wallpapers/random"

  - label: "illustration-additions"
    files: "TheWallpapers/wallpapers/illustrations"

  - label: "enhancement"
    files:
      - ".github/.*"

  - label: "readme_update"
    files:
      - "README.md*"

  - label: "CONTRIBUTION_update"
    files:
      - "CONTRIBUTION.md"
