version: 1
labels:
  - label: "newWallpapers"
    files:
      - "wallpapers/.*"
      
  - label: "enhancement"
    files:
      - ".github/.*"
      
  - label: "readme_update"
    files:
      - "README.md*"
       
