version: 1
labels:
  - label: "anime-additions"
    files:
      - "/TheWallpapers/wallpapers/anime-wallpapers"
  - label: "nature-additions"
    files:
      - "/TheWallpapers/wallpapers/nature-wallpapers"

  - label: "random-additions"
    files:  "./theWallpapers/wallpapers/random"

  - label: "illustration-additions"
    files: "/TheWallpapers/wallpapers/illustration"

  - label: "enhancement"
    files:
      - ".github/.*"

  - label: "readme_update"
    files:
      - "README.md*"

  - label: "CONTRIBUTION_update"
    files:
      - "CONTRIBUTION.md"
