version: 1
labels:
  - label: "newWallpaper"
    files:
      - "wallapapers/*"
      
  - label: "enhancement"
    files:
      - ".github/.*"
      
  - label: "readme_update"
    files:
      - "README.MD*"
       
