version: 1
labels:
  - label: "newWallpapers"
     files:
      - "/wallpapers/.*"
      
  - label: "enhancement"
    files:
      - ".github/.*"
      
  - label: "readme_update"
    files:
      - "README.md*"
    
  - label: "CONTRIBUTION_update"
    files:
      - "CONTRIBUTION.md"
      
  - label: "CCC"
    files:
      - "fh1.c"
      
      
    
       
