version: 1
labels:
  - label: "anime-additions"
    files:
      - "wallpapers/anime-wallpapers/**"

  - label: "enhancement"
    files:
      - ".github/.*"

  - label: "readme_update"
    files:
      - 'README.md'

  - label: "CONTRIBUTION_update"
    files:
      - 'CONTRIBUTION.md'
