name: Labeler
on:
  pull_request:
    branches:
    - main
jobs:
  newWallpaper:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
  
