
name: Labeler
on: [pull_request]

jobs:
    uses: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4 
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        
        newWallpaper:
        - wallpapers/wallpapers/*
        - wallpapers/wallpapers/**/*
