name: Label PR
on:
  pull_request:
    types: [opened, edited]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: netlify/pr-labeler-action@v1.0.0
        if: startsWith(github.event.pull_request.title, 'duplicate , same ')
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          label: 'duplicate'
          
      - uses: netlify/pr-labeler-action@v1.0.0
        if: startsWith(github.event.pull_request.title, 'nature , added in nature')
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          label: 'nature-addition'
          
      - uses: netlify/pr-labeler-action@v1.0.0
        if: startsWith(github.event.pull_request.title, 'anime')
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          label: 'anime-addition'
